### ISSUE TITLE
CLIツール類のbash版追加

### ISSUE THREAD

**Issue by tanakahisateru** [yiijan/yii2-ja#1]
ツール類が `*.bat` なので `*.sh` を追加してMac/Linuxの人でも同じ作業ができるようにしたいです。

**Comment by softark** [comment]
なるほど、確かに。
作ってもらうと助かります。

**Comment by tanakahisateru** [comment]
@softark そのまま移植ですがどうでしょう。実行パーミッションも付けておきました
